
services:
  app:
    build: .
    container_name: fiber_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ALLOW_ORIGINS=${ALLOW_ORIGINS}
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
      - /go/pkg/mod
      - ./tmp:/app/tmp